import Head from 'next/head'
import Header from "./header"
import Footer from "./footer";

export default function Layout({ children }) {
    return (
        <>
            <Head>
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>NextJS Work</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Header/>
            <main>{children}</main>
            <Footer/>
        </>
    );
}
