import Head from 'next/head';
import Article from '@/components/article';

import { getAllPosts } from '@/lib/getAllData';

export async function getStaticProps() {
  const posts = getAllPosts();

  return {
    props: {
      posts,
    },
  };
}

export default function Blog({posts}) {
  return (
    <div>
      <Head>
        <title>NextJS Blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Blog</h1>
	  	{
			posts.map((post) => (
				<Article key={post.slug} className='border-b-2' post={post} />
			))
		}
    </div>
  );
}
