import React, { useState, useEffect } from "react"
import {getAllPosts, getAllPostsByTag} from "@/lib/getAllData";
import Head from "next/head";
import Article from "@/components/article";

export async function getStaticPaths() {
    const posts = getAllPosts();
    const tags = new Set(posts.flatMap((post) => post.tags));

    return {
        paths: [...tags].map((tag) => {
            return {
                params: {
                    tag
                }
            }
        }),
        fallback: false,
    };
}

export async function getStaticProps({ params: { tag } }) {
    const posts = getAllPostsByTag({tag});

    return {
        props: {
            posts,
            tag
        },
    };
}

export default function Tag({ posts, tag }) {

    const numberPosts = 2

	// State for the list
	const [list, setList] = useState([...posts.slice(0, numberPosts)])

	// State to trigger oad more
	const [loadMore, setLoadMore] = useState(false)

	// State of whether there is more to load
	const [hasMore, setHasMore] = useState(posts.length > numberPosts)

	// Load more button click
	const handleLoadMore = () => {
		setLoadMore(true)
	}

	// Handle loading more articles
	useEffect(() => {
		if (loadMore && hasMore) {
		const currentLength = list.length
		const isMore = currentLength < posts.length
		const nextResults = isMore
			? posts.slice(currentLength, currentLength + numberPosts)
			: []
		setList([...list, ...nextResults])
		setLoadMore(false)
		}
	}, [loadMore, hasMore]) //eslint-disable-line

	//Check if there is more
	useEffect(() => {
		const isMore = list.length < posts.length
		setHasMore(isMore)
	}, [list]) //eslint-disable-line


    return (
        <div>
            <Head>
                <title>NextJS Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/public/favicon.ico" />
            </Head>
            <section className='px-6'>
                <div className='max-w-4xl mx-auto'>
                    <h1 className='text-3xl font-bold mb-6 p-4'>All `{tag}` posts</h1>
                    {list.map((post) => (
                        <Article key={post.slug} className='border-b-2' post={post} />
                    ))}
                </div>
                {hasMore ? (
				<div><button onClick={handleLoadMore}>Еще статьи</button></div>
				) : (
                    <div><button disabled>Больше нет статей</button></div>
                )}
            </section>
        </div>
    )
}
